Repository ThaiTuan123/mocdecor, pull requests merged in 2024-11, with the labels that each got.

#94 apply api and fix bug no 69
  src/app/home/page.tsx
  src/components/card/CategoryCard.tsx
  src/components/carousel/Carousel.tsx
  src/components/popup/ProductPopup.tsx
  src/components/product/ProductCard.tsx
  src/components/product/ProductCardWhite.tsx
  src/recoil/hooks/useFetchCategories.ts
  src/types/category.d.ts
  src/types/categoryCardProps.d.ts
  src/types/categoryType.ts
  tailwind.config.ts
Labels: review

#123 fix bug no #103
  src/app/app.css
  src/components/tab/Tab.tsx
Labels: review

#122 fix bug no #105
  src/app/contact/page.tsx
  src/app/home/page.tsx
  src/components/inputs/TextInput.tsx
  src/components/texts/TextContent.tsx
  tailwind.config.ts
Labels: review

#121 fix bug no #111
  src/app/not-found.tsx
  src/components/header/Header.tsx
  src/configs/languages/index.ts
Labels: review

#127 fix bug response popup
  src/components/button/CancelButton.tsx
  src/components/carousel/ProductCarousel.tsx
  src/components/popup/ProductPopup.tsx
  src/utils/constants.ts
Labels: review

#128 change QuantitySelector when plus
  src/components/popup/ProductPopup.tsx
Labels: review

#129 Fix bug các dòng sản phẩm call api sử dụng useState sang sử dụng recoil
  src/app/home/page.tsx
  src/recoil/atoms/categoryErrorAtom.ts
  src/recoil/hooks/useCategories.ts
  src/recoil/hooks/useFetchCategories.ts
Labels: help wanted

#130 fix bug map google contact page
  src/utils/helpers/googleMapsEmbedHelper.tsx
Labels: review

#132 Fix bug Banner homepage change from useState to Recoil
  src/components/carousel/Carousel.tsx
  src/recoil/atoms/activeIndexStateAtom.ts
  src/recoil/hooks/useCarouselItems.ts
Labels: review

#136 change image homepage to using image nextjs
  src/components/card/MotionImageCar.tsx
  src/components/header/Header.tsx
Labels: review

#138 update logic cart
  next.config.mjs
  src/app/products/[type]/[kind]/page.tsx
  src/components/Cart/Cart.tsx
  src/components/gridView/ProductGrid.tsx
  src/components/gridView/ProductGridFrame.tsx
  src/components/header/Header.tsx
  src/components/index.tsx
  src/components/popup/ProductPopup.tsx
  src/recoil/atoms/cartAtom.ts
  src/recoil/hooks/useCart.ts
  src/recoil/hooks/useListProducts.ts
  src/services/api.ts
  src/types/cartType.ts
  src/utils/constants.ts
  src/utils/index.ts
Labels: Create new
